name: NPM Package
on:
  push:
    branches:
      - main
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Install global dependencies
        run: npm i -g yarn typescript
      - name: Install local dependencies
        run: yarn
      - run: git config --global user.email "arcaela.reyes@gmail.com"
      - run: git config --global user.name "Alejandro Reyes"
      - name: Publishing
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
