name: NPM Package
on:
  push:
    branches:
      - main
jobs:
  preparing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
  installing:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: npm ci
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Packet Codes
        run: npm run commit
        env: 
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}