name: NPM Package
on:
  push:
    branches:
      - main
jobs:
  preparing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
  installing:
    runs-on: ubuntu-latest
    steps:
      - name: Install Global dependencies
        run: npm i -g yarn typescript
      - name: Install dependencies
        run: yarn
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: TypeScript
        run: tsc
      - name: Update Version
        run: npm version minor
      - name: Packet Codes
        run: npm publish --access=public
        env: 
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}